### PR TITLE
Solved error

### LINKED ISSUE #3: Exception in to_string
Hello, when I try to test the plugin with ethereum using the transactions option, I've got the next error:

08:20:24.341 [[main]<blockchain] ERROR logstash.pipeline - A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Blockchain protocol=>"ethereum", host=>"localhost", port=>8545, start_height=>100000, granularity=>"transaction", id=>"914548ba0e9a44d00cd34a89a01e2eded45ebc9e-1", enable_metric=>true, codec=><LogStash::Codecs::JSON id=>"json_75f68452-20b5-4eb3-a87e-2a981742466c", enable_metric=>true, charset=>"UTF-8">, interval=>0>
  Error: undefined method `to_string' for 42:Fixnum

### PR DESCRIPTION
**Pull request by hendry19901990**
Added validation to Fix #3

### CODE REVIEW

**Review by consulthys — CHANGES_REQUESTED** [review]
Can you make sure that the code indentation is correct? As you can see, it is not the case, maybe you're using tabs instead of spaces? Anyway, thanks much for your PR.

**Comment by hendry19901990** [comment]
excuse me, would you like that i improve the identation in the code ?

**Review by consulthys — CHANGES_REQUESTED** [review]
Still not good sorry, I still see tabs in there ;-) Make sure you only use spaces for indentation. Thank you

**Comment by hendry19901990** [comment]
ready, i did it https://github.com/hendry19901990/logstash-input-blockchain/blob/6005434cb8c7c1f154d04ef043213dcf9e617d0d/lib/logstash/inputs/protocols/ethereum.rb#L54

**Pull request merged**
